image:
  file: .gitpod.Dockerfile

tasks:
  - init: ionic start truckroute
    command: 'ionic serve'

vscode:
  extensions:
    - Mikael.Angular-BeastCode@10.0.3:RJ2bMuvUpAuD63D5osKHMg==
    - fivethree.vscode-ionic-snippets@2.2.2:Ply5R23KZJUx7j67niwLJQ==